//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TallerSucursalEstacion
    {
        public int id_taller { get; set; }
        public int id_taller_sucursal { get; set; }
        public int id_estacion { get; set; }
        public int id_usuario_estacion { get; set; }
        public Nullable<bool> activa { get; set; }
    
        public virtual TallerSucursal TallerSucursal { get; set; }
    }
}
