//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TallerParametro
    {
        public int id_taller { get; set; }
        public string id_parametro { get; set; }
        public string nombre_parametro { get; set; }
        public string valor_parametro { get; set; }
        public string descripcion_parametro { get; set; }
    
        public virtual Taller Taller { get; set; }
    }
}
