//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoParte
    {
        public int id_taller { get; set; }
        public int id_trabajo { get; set; }
        public string id_parte { get; set; }
        public Nullable<decimal> precioExtra { get; set; }
        public Nullable<short> cantidad { get; set; }
    
        public virtual Parte Parte { get; set; }
        public virtual Trabajo Trabajo { get; set; }
    }
}
