//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajo()
        {
            this.TrabajoExterno = new HashSet<TrabajoExterno>();
            this.TrabajoManoObra = new HashSet<TrabajoManoObra>();
            this.TrabajoPago = new HashSet<TrabajoPago>();
            this.TrabajoParte = new HashSet<TrabajoParte>();
        }
    
        public int id_taller { get; set; }
        public int id_trabajo { get; set; }
        public string id_cliente { get; set; }
        public string matricula_id { get; set; }
        public string creador { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> tipoFactura { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Taller Taller { get; set; }
        public virtual TipoFactura TipoFactura1 { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoExterno> TrabajoExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoManoObra> TrabajoManoObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoPago> TrabajoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoParte> TrabajoParte { get; set; }
    }
}
