//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoPago
    {
        public int id_taller { get; set; }
        public int id_trabajo { get; set; }
        public int id_medioPago { get; set; }
        public int id_linea { get; set; }
        public decimal monto { get; set; }
    
        public virtual MedioPago MedioPago { get; set; }
        public virtual Trabajo Trabajo { get; set; }
    }
}
