//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.ClienteVehiculo = new HashSet<ClienteVehiculo>();
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public int id_taller { get; set; }
        public string matricula_id { get; set; }
        public string modelo_id { get; set; }
        public string marca_id { get; set; }
        public string motorcc { get; set; }
        public string serial { get; set; }
        public Nullable<int> transmision { get; set; }
        public Nullable<int> tipoGas { get; set; }
        public string color { get; set; }
        public bool aireAc { get; set; }
        public string observaciones { get; set; }
        public string modelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteVehiculo> ClienteVehiculo { get; set; }
        public virtual Modelo Modelo1 { get; set; }
        public virtual Taller Taller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}
